apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hello-world.fullname" . }}
  labels:
    {{- include "hello-world.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "hello-world.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "hello-world.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "hello-world.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
            failureThreshold: 1
          readinessProbe:
            httpGet:
              path: /
              port: http
            failureThreshold: 1
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
        - name: storage-consumer
          image: busybox
          command: ["/bin/sh", "-c", "trap 'exit 0' SIGTERM; while true; do sleep 1; done"]
          resources:
            limits:
              ephemeral-storage: "2Gi"
            requests:
              ephemeral-storage: "1Gi"
